### ISSUE TITLE
Number validation not working in Italian and Arabic

### ISSUE THREAD

**Issue by VecchioIdraulico** [robisim74/angular-l10n-sample#1]
To replicate: 

1. 1. Clone & install repository, run via npm start, open localhost to browse
2. Go to validation via the menu; select US or GB validation
3. Enter number (used 4.33) in validation form; submit: See validation pass
4. Switch to Italian or Arabic; repeat process: Validation fails.
5. Enter number and validate in US/GB; switch to IT/AR; click submit: Number's value reported as NaN.

**Comment by robisim74** [comment]
I'm sorry, but I can not re-create this problem. The online version built with AoT and the local version using dev-server work properly.

But I have a doubt: are you always entering _4.33_? Because in this case it is correct: US/GB use the point, IT uses the comma, and for Arabic you have to insert the number in Arabic, for example: _٣٫١٤_

**Comment by robisim74** [comment]
Another thing: clean everytime the field before/after changing language.
